# Generated by Django 5.1.1 on 2024-10-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNotificationPreferance',
        ),
    ]
