# Generated by Django 5.1.1 on 2024-10-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_role_permissions_alter_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
