# Generated by Django 5.1.1 on 2024-10-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_role_customuser_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('create_report', 'Can create a report'), ('delete_report', 'Can delete a report'), ('view_report', 'Can view a report')]},
        ),
    ]
